spring.application.name=organized-scan

# Postgres local (ajuste conforme seu compose)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA/Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db

# Thymeleaf: enable hidden _method (DELETE/PUT)
spring.mvc.hiddenmethod.filter.enabled=true

# OAuth (quando for testar de novo)
spring.security.oauth2.client.registration.github.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.github.redirect-uri=${REDIRECT_URI}

